@extends('layout.main')

@section('content')
    <div class="container">
        <div class="img-container d-flex justify-content-center m-6">
            <img src="https://media3.giphy.com/media/uULru6cnBO4gM/giphy.gif?cid=ecf05e47cn5zkw686jz9zxzqmty4t710xg1ul04tjnd1evj8&ep=v1_gifs_search&rid=giphy.gif&ct=g" alt="gif-welcome">
        </div>
        <h1 class="text-center text-warning">Welcome to Artists & Museums DB</h1>
        <p class="text-center">Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt iure eius animi. Blanditiis aut praesentium dolore, voluptates minus dolorum consequuntur earum, ad in laudantium totam numquam voluptatem excepturi alias ipsam perferendis modi sed id, veniam quaerat rerum voluptas? Asperiores possimus voluptatum quasi? Nostrum eaque corporis optio blanditiis a quia, facilis, cum nobis ipsam, voluptatum perspiciatis amet eligendi. Deleniti quos fugit modi itaque! Voluptas vel natus, neque maxime culpa provident alias vero temporibus error dolores quasi repudiandae consequuntur similique, omnis nobis libero assumenda quis autem minus deserunt quisquam eos accusamus? Ipsum dolorem, officiis voluptatum veniam hic repellendus vel voluptate ad magni ut id laudantium pariatur adipisci velit perspiciatis aliquid? Rem cum non obcaecati accusamus a eaque odio sapiente porro nam modi dolorum corporis ullam excepturi autem labore assumenda totam incidunt similique provident eligendi, corrupti architecto soluta. Velit culpa assumenda dignissimos quaerat. Odit nulla a, enim dolorum asperiores consequuntur iure eaque fuga suscipit quia perspiciatis saepe aliquid perferendis nam sapiente sequi at voluptatibus fugit distinctio. Provident in perferendis error suscipit sit omnis. Sunt odit provident id, fugit expedita eum perferendis unde beatae sit modi quae, molestias eaque in ratione optio earum eius eveniet. Eum modi vitae perspiciatis magnam iusto architecto officia et ipsa libero itaque temporibus voluptatibus, fuga molestiae molestias minus labore nihil quo laborum obcaecati nulla, provident autem quis, laudantium dicta. Omnis perspiciatis ipsa tenetur maiores nihil! Ipsam sed voluptatum magnam excepturi culpa facere quidem nisi dolores similique dolore, id, non eius, fugit corporis saepe tenetur? Rem, repudiandae. Quo mollitia labore nesciunt expedita neque error beatae enim cum maxime nemo iusto culpa architecto voluptate nisi possimus, deserunt animi ullam ad! Minima, eligendi aspernatur. Molestiae eius culpa in fugiat nostrum illo quae saepe libero et, molestias illum tempore dignissimos? Assumenda autem consequatur fugiat aliquam a blanditiis, culpa at, veniam facilis quibusdam corporis?</p>
    </div>
@endsection
